export default function Head() {
  return (
    <>
      <title>parkgain</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="keywords" content = "박가인, parkgain"/>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/logo.png" />
    </>
  );
}
